version: "3.8"

services:
  app: 
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: sso-app
    ports: 
      - "8081:8081"
      - "8082:8082"
    depends_on:
      - postgre
    networks:
      net:
        ipv4_address: 10.10.11.3
  postgre:
    image: postgre:16-alpine
    container_name: sso-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=UserBeer
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      net:
        ipv4_address: 10.10.11.2
volumes:
  postgres_data:
networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 10.10.11.0/8
          gateway: 10.10.11.1
