// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20250615111747_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Model.Entities.ApiKey", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateExpire")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Uid");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("Model.Entities.Application", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DateBreak")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateLastCheck")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWork")
                        .HasColumnType("boolean");

                    b.Property<string>("Login")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<int>("TypeApplication")
                        .HasColumnType("integer");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("Uid");

                    b.ToTable("Applications");

                    b.HasData(
                        new
                        {
                            Uid = new Guid("79e32f14-c263-4a2e-9f1c-0185e8c03ce6"),
                            Description = "Приложения для списка задач, которые нужно сделать для восстановления Волги",
                            Ip = "195.133.28.197",
                            IsActive = true,
                            IsWork = true,
                            Name = "Volga-Tracker",
                            Port = 10,
                            TypeApplication = 2,
                            Version = "v1"
                        },
                        new
                        {
                            Uid = new Guid("4e0129a9-fd5e-4110-95ff-cd19b43d3c72"),
                            Description = "База данных для волга-трекер",
                            Ip = "195.133.28.197",
                            IsActive = true,
                            IsWork = true,
                            Login = "postgres",
                            Name = "volga_tracker",
                            Password = "3G4rc3093jBlYgEaha/fOw==",
                            Port = 5432,
                            TypeApplication = 3,
                            Version = "v1"
                        },
                        new
                        {
                            Uid = new Guid("3f597bd4-b9dd-4788-aa02-8db6125ef945"),
                            Description = "База данных для пользователей",
                            Ip = "195.133.28.197",
                            IsActive = true,
                            IsWork = true,
                            Login = "postgres",
                            Name = "UserBeer",
                            Password = "3G4rc3093jBlYgEaha/fOw==",
                            Port = 5432,
                            TypeApplication = 3,
                            Version = "v1"
                        });
                });

            modelBuilder.Entity("Model.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateExpire")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Uid");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Model.Entities.Role", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationUid")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Uid");

                    b.HasIndex("ApplicationUid");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Model.Entities.User", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApiKeyUid")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("HashPassword")
                        .HasColumnType("text");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActiveCode")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsApiKey")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPass")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUserPass")
                        .HasColumnType("boolean");

                    b.Property<int>("Language")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<Guid?>("RefreshTokenUid")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Salt")
                        .HasColumnType("bytea");

                    b.HasKey("Uid");

                    b.HasIndex("ApiKeyUid");

                    b.HasIndex("RefreshTokenUid")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Uid = new Guid("4a087b1a-0195-493e-8324-4c26ebc0c4eb"),
                            Code = "000000",
                            DateCreate = new DateTime(2025, 6, 15, 11, 17, 46, 115, DateTimeKind.Utc).AddTicks(1159),
                            FirstName = "Дмитрий",
                            Ip = "127.0.0.1",
                            IsActive = true,
                            IsActiveCode = false,
                            IsApiKey = false,
                            IsPass = false,
                            IsUserPass = true,
                            Language = 0,
                            LastName = "Патюков",
                            Login = "Totohka",
                            MiddleName = "Анатольевич"
                        },
                        new
                        {
                            Uid = new Guid("5436fc04-a7d3-4a45-ad7f-861c1eba0ed0"),
                            Code = "000000",
                            DateCreate = new DateTime(2025, 6, 15, 11, 17, 46, 115, DateTimeKind.Utc).AddTicks(3105),
                            FirstName = "Эдуард",
                            Ip = "127.0.0.1",
                            IsActive = true,
                            IsActiveCode = false,
                            IsApiKey = false,
                            IsPass = false,
                            IsUserPass = true,
                            Language = 0,
                            LastName = "Новиков",
                            Login = "Nedoff",
                            MiddleName = "Дмитриевич"
                        },
                        new
                        {
                            Uid = new Guid("09814dd3-e028-40ae-81ee-6b16653d57fa"),
                            Code = "000000",
                            DateCreate = new DateTime(2025, 6, 15, 11, 17, 46, 115, DateTimeKind.Utc).AddTicks(3115),
                            FirstName = "Степан",
                            Ip = "127.0.0.1",
                            IsActive = true,
                            IsActiveCode = false,
                            IsApiKey = false,
                            IsPass = false,
                            IsUserPass = true,
                            Language = 0,
                            LastName = "Кондрашов",
                            Login = "Stepan",
                            MiddleName = "Андреевич"
                        },
                        new
                        {
                            Uid = new Guid("ad63676a-0994-427d-a639-17cb7ccf1fc2"),
                            Code = "000000",
                            DateCreate = new DateTime(2025, 6, 15, 11, 17, 46, 115, DateTimeKind.Utc).AddTicks(3120),
                            FirstName = "Кирилл",
                            Ip = "127.0.0.1",
                            IsActive = true,
                            IsActiveCode = false,
                            IsApiKey = false,
                            IsPass = false,
                            IsUserPass = true,
                            Language = 0,
                            LastName = "Шилов",
                            Login = "Kirill",
                            MiddleName = "Александрович"
                        });
                });

            modelBuilder.Entity("Model.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleUid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserUid")
                        .HasColumnType("uuid");

                    b.HasKey("Uid");

                    b.HasIndex("RoleUid");

                    b.HasIndex("UserUid");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Model.Entities.WhiteIp", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApiKeyUid")
                        .HasColumnType("uuid");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Uid");

                    b.HasIndex("ApiKeyUid");

                    b.ToTable("WhiteIps");
                });

            modelBuilder.Entity("Model.Entities.Role", b =>
                {
                    b.HasOne("Model.Entities.Application", "Application")
                        .WithMany("Roles")
                        .HasForeignKey("ApplicationUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Model.Entities.User", b =>
                {
                    b.HasOne("Model.Entities.ApiKey", "ApiKey")
                        .WithMany()
                        .HasForeignKey("ApiKeyUid");

                    b.HasOne("Model.Entities.RefreshToken", "RefreshToken")
                        .WithOne("User")
                        .HasForeignKey("Model.Entities.User", "RefreshTokenUid");

                    b.Navigation("ApiKey");

                    b.Navigation("RefreshToken");
                });

            modelBuilder.Entity("Model.Entities.UserRole", b =>
                {
                    b.HasOne("Model.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Model.Entities.WhiteIp", b =>
                {
                    b.HasOne("Model.Entities.ApiKey", "ApiKey")
                        .WithMany()
                        .HasForeignKey("ApiKeyUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiKey");
                });

            modelBuilder.Entity("Model.Entities.Application", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Model.Entities.RefreshToken", b =>
                {
                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Model.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
