// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20250301051617_AddLanguage")]
    partial class AddLanguage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Model.Entities.ApiKey", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateExpire")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Uid");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("Model.Entities.Application", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DateBreak")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateLastCheck")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWork")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("Uid");

                    b.ToTable("Applications");

                    b.HasData(
                        new
                        {
                            Uid = new Guid("1162c098-330f-46f1-ae8a-110625ac0c64"),
                            Description = "Приложения для списка задач, которые нужно сделать для восстановления Волги",
                            Ip = "10.10.10.10",
                            IsActive = true,
                            IsWork = true,
                            Name = "Volga-Tracker",
                            Port = 10,
                            Version = "v1"
                        });
                });

            modelBuilder.Entity("Model.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateExpire")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Uid");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Model.Entities.Role", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationUid")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Uid");

                    b.HasIndex("ApplicationUid");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Model.Entities.User", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApiKeyUid")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("HashPassword")
                        .HasColumnType("text");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActiveCode")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsApiKey")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPass")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUserPass")
                        .HasColumnType("boolean");

                    b.Property<int>("Language")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<Guid?>("RefreshTokenUid")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Salt")
                        .HasColumnType("bytea");

                    b.HasKey("Uid");

                    b.HasIndex("ApiKeyUid");

                    b.HasIndex("RefreshTokenUid")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Uid = new Guid("7a1bda3f-9543-4208-aacd-2dd6d07a5d5a"),
                            Code = "000000",
                            DateCreate = new DateTime(2025, 3, 1, 5, 16, 16, 128, DateTimeKind.Utc).AddTicks(8792),
                            FirstName = "Дмитрий",
                            Ip = "127.0.0.1",
                            IsActive = true,
                            IsActiveCode = false,
                            IsApiKey = false,
                            IsPass = false,
                            IsUserPass = true,
                            Language = 0,
                            LastName = "Патюков",
                            Login = "Totohka",
                            MiddleName = "Анатольевич"
                        },
                        new
                        {
                            Uid = new Guid("857c9bd8-6e11-4195-b4a8-fe3b94502856"),
                            Code = "000000",
                            DateCreate = new DateTime(2025, 3, 1, 5, 16, 16, 129, DateTimeKind.Utc).AddTicks(1262),
                            Email = "test@gmail.com",
                            FirstName = "Эдуард",
                            Ip = "127.0.0.1",
                            IsActive = true,
                            IsActiveCode = false,
                            IsApiKey = false,
                            IsPass = false,
                            IsUserPass = true,
                            Language = 0,
                            LastName = "Новиков",
                            Login = "Nedoff",
                            MiddleName = "Дмитриевич"
                        },
                        new
                        {
                            Uid = new Guid("2fbd2424-4f07-4262-a85a-ddad143636b2"),
                            Code = "000000",
                            DateCreate = new DateTime(2025, 3, 1, 5, 16, 16, 129, DateTimeKind.Utc).AddTicks(1275),
                            Email = "test2@gmail.com",
                            FirstName = "Степан",
                            Ip = "127.0.0.1",
                            IsActive = true,
                            IsActiveCode = false,
                            IsApiKey = false,
                            IsPass = false,
                            IsUserPass = true,
                            Language = 0,
                            LastName = "Кондрашов",
                            Login = "Stepan",
                            MiddleName = "Андреевич"
                        },
                        new
                        {
                            Uid = new Guid("b2b612b0-0149-4b85-a669-96cd7c4926e8"),
                            Code = "000000",
                            DateCreate = new DateTime(2025, 3, 1, 5, 16, 16, 129, DateTimeKind.Utc).AddTicks(1282),
                            Email = "test3@gmail.com",
                            FirstName = "Кирилл",
                            Ip = "127.0.0.1",
                            IsActive = true,
                            IsActiveCode = false,
                            IsApiKey = false,
                            IsPass = false,
                            IsUserPass = true,
                            Language = 0,
                            LastName = "Шилов",
                            Login = "Kirill",
                            MiddleName = "Александрович"
                        });
                });

            modelBuilder.Entity("Model.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleUid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserUid")
                        .HasColumnType("uuid");

                    b.HasKey("Uid");

                    b.HasIndex("RoleUid");

                    b.HasIndex("UserUid");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Model.Entities.WhiteIp", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApiKeyUid")
                        .HasColumnType("uuid");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Uid");

                    b.HasIndex("ApiKeyUid");

                    b.ToTable("WhiteIps");
                });

            modelBuilder.Entity("Model.Entities.Role", b =>
                {
                    b.HasOne("Model.Entities.Application", "Application")
                        .WithMany("Roles")
                        .HasForeignKey("ApplicationUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Model.Entities.User", b =>
                {
                    b.HasOne("Model.Entities.ApiKey", "ApiKey")
                        .WithMany()
                        .HasForeignKey("ApiKeyUid");

                    b.HasOne("Model.Entities.RefreshToken", "RefreshToken")
                        .WithOne("User")
                        .HasForeignKey("Model.Entities.User", "RefreshTokenUid");

                    b.Navigation("ApiKey");

                    b.Navigation("RefreshToken");
                });

            modelBuilder.Entity("Model.Entities.UserRole", b =>
                {
                    b.HasOne("Model.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Model.Entities.WhiteIp", b =>
                {
                    b.HasOne("Model.Entities.ApiKey", "ApiKey")
                        .WithMany()
                        .HasForeignKey("ApiKeyUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiKey");
                });

            modelBuilder.Entity("Model.Entities.Application", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Model.Entities.RefreshToken", b =>
                {
                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Model.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
